# Site settings
title: Minimal Jekyll Bootstrap
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Don't write a description here. It looks ugly.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: overlandandseas
github_username:  overlandandseas

# Build settings
markdown: kramdown
